//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKHP.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKy
    {
        public int MaDK { get; set; }
        public string MaSV { get; set; }
        public string MaLop { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
    
        public virtual LopHoc LopHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
