//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DKHP.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHoc()
        {
            this.DangKies = new HashSet<DangKy>();
        }
    
        public string MaLop { get; set; }
        public string MaMon { get; set; }
        public string MaGV { get; set; }
        public string LichHoc { get; set; }
        public Nullable<int> SiSoToiDa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DangKy> DangKies { get; set; }
        public virtual GiangVien GiangVien { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
